language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:

install: true

script: mvn clean verify -P shade,sources,javadoc -Djava.version=1.6

after_success:
after_failure:
