language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

before_install:

install:

script: mvn clean verify -P shade -P sources -P javadoc -Djava.version=1.6

after_success:
after_failure:
