language: java

env:
  global:
    # SONATYPE_USERNAME
    - secure: "GdfZA+xgGEEn1Qv0Tq3GTsWG0XoxHmXN/SmfU6tHRjQvdhSDy6uBy8LA7SZclSVABzkeIorf7TH+oJbZUyA+209FyhZe0dIIlpr3d7wWNt0BKd6nCJkUp4bjgxn+tRGIhwGH5PcmV7n2rpPSRrP/M2zuK0RK6wiCSZED9Ie7i3EnaciQpuQEWNflPWcFeiiN0mWP+C+cYMvxHevPF5pCTgrkJK2+EyfAmhGAw2N3a02L0a33rEffgFHT2byfTWONcdW2EhwV2r0XQHWuO6CMG8kFxkvmlugLbuWeQdtuntP2BNAOyOIywhsxcFBioEdAFYjtdpRBkouDs4z8w5ILg5sXhUKUoWqIGHN9NMOD6FwqhLLFPyzGSDkMbRTZ5g+3hVA8SnPvMTAsl4SnR8P79X08vUKwk9dIZYIvlOgcAhXWZ/CfZKGSVXw5mp7VeLtDEEoUbcbrPjJWbAYBYAK4rX6La20dmmT4VM3S+6DNo6rMJDP3bLwIBBZNnJdF+eSdqO5/x6Tej3OAVz5mx0UHXRk2lTZKwKk+u3VEXoKDIIZX0qDWry/EUD1WpiPnrnokvl79HWmeIF4GvmS2gh0a7BYfns4UtQPgzt37Rxfp8NBlNyTJNM8KIDc3cj6QKw9e8Lpcxk5kff2OLA6TQyBI3aVtZobBXgFXNvKBQaXMbWI="
    # SONATYPE_PASSWORD:
    - secure: "OFLoHr5S4G4LmxVj571ulX3uFe1HYXhaZjVVzOECUIVXtb8tmTFsavtuYFMgH0K6+rrzJxy30IEXf6nH2O7G6lx9zV39ynch30Vqe7IPt/g5UjFu8aew9uFeOnViqYZip3woS9pTLxepxgeeG7/a2FCt9pNXr6mkFhJ/enePyENM7mx2E5vFd++blH/Qlv3d23TvbpCldFyWW2TrVpNFIoHPgF59P2ArFqhBbP/7yfs1jTyAZbojGF26Q4zqkJJBGAffaFfdA77qIid1m+8Bp2hCZoAn1I0FP3UsH25iUmEc4jvbszzP9zpmhG7ECYtG98C3u3OoelgPMZ/TNgxQvB5afjaYc98l0eZT5FrO/7zmJxwt3olvZDlB3zDX7HbhK1LPrAezEZ3XAoNFoGKc3z9YxpuswOB1dQ8iM583njxZ8+D+488VUZi9RP9wd5aUBAAaormIIeX+pWoPMDwTLnNih4SKxh3sLyfoCCyBwC3zuude/vLuaj8R8QYIC4GTSIaExc+VcaJemwY6QSJUeQGtM9N1+zDFTAsoiAIxJa1MBweQasgRbw3rZK6aLD+E4+yCkVKmjinXpVDy5CYNqRcYgDgIoD/Jy4zBm/SkCdtSvCA6Ow+Ug0U89MPgNa1DJcJNRD7ya0dQyTDsUyb9721NruVMMUiGKJDD7Cmtp4E="
    # GPG_PASSPHRASE:
    - secure: "KCLtNVqQW4ek16rr/FEmbkIOIfWz0ccP/RIYeYAhiDCxAoAg+tZaYEHBufHu34EGB3j/LOTjmJJENGPfaRbmc2xaIKgdqppmxVt1oWrgfgEkf3iCQCcvm2eFqCbpDVNZ94exIas5WNcRz41ESzXxqtVGGyF/rZ1WjOC/c3D6Cb/g2CuqmkBTSMWt7EVKJvpj7LJvbYPSvCkRAC3aRjd19a975+w7bekNLQcFKoxDXFB0hNJik5VLT/KN5P1+i0cx7JU/49qJLy80AR9CJGlumvTng3rldw+kQica9Ca/IdB0Bz+J/JnUebBdQocqJOW7sTP8TdxdWyX/mMRXFPvKs1uwu4ru+wpXdt0KFfUrSKfhDAeSxjATq5kFeERw/kplrwCYW2BHHUM1vupThV1Knbr5ORy3zK9M6kl4ybB2TfZXDIgw8N1x1bvFijvNErq5Xq0eIGuYRxXJoprMYT4431T+cfESeR8k+PTtqCHuizF43B4on/wYELXPaNig2+o/7J/N7T9HxrafeHuz60hiLdrLPJjs+fXFeRMXlDUkmJ6spVCx52FrGbhpRvcQgJRs9lBF7CkKvyE3qHlj1VqoCgFHkB4tDx8cK807lXpNpdM/HkMfNrtOb9YK6VMaIgq8dW3f7ZoIjdmOmzXT1a6VtK6c/3ewJc2yz2sBBW8qiX4="
    # ENCRYPTION_PASSWORD:
    - secure: "MHzTfkDWNN9UfpAEqzh4QLPKbv2aJWjtnp3xh7ab+LuesuuRBlUDlHkR3It2i4AjZimvlbFNfQdclxF+PtTFyd7DWXdNDt5V5fyH37B4xvBlD0sq6gADQC5T9mQqmdOGY/w3GRpYIztM9+NC0svNNORixOlkuArW7IpBMoD6A70KCL7AT1dlj9DHcoQOOO3qd4B8UgyjuEOAJ7K3leYNRCwCDyf/eqKKcDXbdY9VSub5nXjM4s63zbNjoirXgiU/E8ed9fbff03Z+joXi55xAUGxuYCGFJkObeib3bPEPlplq3vwiQ3ftVWuVg1ux2B9r3+/YFMtbWd54Z8AMr+gSxiFSLNsbK88YQNMSAAgHOCHWxH4ACDUuFqh8kRwhQnOlCNn0Ok1e/QGDwIVGJdU5OphnaVfNaKWG/iaHdbgsiHO6nkKwfpHcvYAkFk0yUBG2hgZcJAuowvgKr7Ehj/5xpcPDsxJVap0Ul3Z5B1BZI4XJbLO6sP0H6+n3I1mbGbI7zi8rfYCeYFbViLrnLFW9lZbniggWv2JnvifvpjHecWcoBg8RwLt+el4D65GRd6WQozjYZ9CzojUot38SSj59FSkn+gLzj/HUuOuGh0KH7A29NcgHjEJtILq0xiryG9Buzfz1s8gJV4o0rTs3OHgZsEaRreU4harQynpCFwULy8="

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

cache:
  directories:
  - $HOME/.m2

before_install:
  - bash .travis/update_version.sh
  - bash .travis/decrypt_keys.sh

install: true

script: bash .travis/build.sh

after_success: bash .travis/remove_keys.sh

after_failure: bash .travis/remove_keys.sh

deploy:
  provider: releases
  api_key:
    secure: vB0d2RdSz/o1qy56tqM+/vbAB7zpIJkYU/TWHhXYUbYDEEcPlseY1hpRYGSN09x0LHBLNpZSxfVPdwAagoAVWMC7YlSSJoV1W2vwicleILEywxGkZs0oB2xf200W78l43iYdnwWZa/PyihcsT+zWffiX3l0Th26Rs4AuPtWyMbBSABi1js0sR3Y036WBUF04NXaTig6fvvTZ+FEGLrRDTH6R+td2VJ4V7FlUV1FBMt3hMUfx0q3QFxdg1y5EQWPPXu3PFCcXKsU/ckK63ghJikn8N+R6Z9mPzkxbQZkuLbufAWww/a0BNc+UoyTbAbx3e5aMwNo6xyaymyKYDYdPCuGvddd1hgSMh+fDCxraXQLxemsT+fcHtc1ALrYc+ITtFGqagyS3zaodO+Jwvh7q13QRIjYyNVP76ivD7OBcWLvaVEe+AHcHudnocgBq58KGcPTXc9EaEdehdczmHE5lhEgkyuLAeieVmkX5kQvT0ciHv3BSiHTA2B5kjYy0+KvB8g0srr7ifBnT/d7IVL2NDoT8EntS2ZFrkUY1Dm/lsrm4Ho9e/FcZBZbPDsC+GAksUN6b96F438lWjUGHNM95KB9Ohno0+MCemD7onKU0ZM1x/K7CWez7wUp0gx0UQ8mARYvetp5BEBw/aD+L6Ms0ybcMVVlUqa9WcF8e36nssMs=
  file_glob: true
  file:
    - /home/travis/build/arturolszak/hycube/target/hycube-*.jar
    - /home/travis/build/arturolszak/hycube/target/hycube-*.zip
    - /home/travis/build/arturolszak/hycube/documentation/*
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

after_deploy:

after_script: bash .travis/clean_after_script.sh
