language: java

env:
  global:
    - SONATYPE_USERNAME=hycube
    #SONATYPE_PASSWORD
    - secure: "dnOxvALDxzUeiueR61d7gVWgf7u/t3PDLRF5Xs3UNB9WkKhhIBhePVMn0GEnbEeWKUBlH5wEAkdGSJhfwZWiD0qH6vvTQyzmCm+FiCMPabRxdKDvF9gLMcRIlCjvw0wxbT26Qn+UjGFjaYixJdNqPpoj+2Bcx9fkjq9jyGm01d5Y3psJNh//HLw9asOwvCzGd9Xpzlt2mGaXESxhqBYuX2/CJGQ07o9qG47HNBvV0Ubr6SFvGm3sfVMPJbhmZxe6j7iy2Nh7zNXUbawXLiLT0yJIExkKpJvKeMdUIJ2oaTsv4bBAvMKQYvuq7GipymZDBNr1NdCAVi0aNE9Ke6rtvk10dVhXYxwtBFwbaWWnpDmQtKGuluUTHsAfCwpKbqaMc29qYSD8jEHJEscXVtMsNSknOZrVbZBO21cyzZhKaSeugvCYsqvij54ESWLulqhjcxh8G4urUUYOkJN6X7sQBT1RIT6JQm7yaFuGLarQd7TEOnsIFeD+jijeLMsLxPXQlEBdnw5Ah4XGC7LnKCE+IiRbQB8rvsFHwE2sPLPmXDQEmt9wvDi2jizd231weO8c70RnpwZSHRcxXsKsWUUKSafwji9RLTx7WgXc01VYGqaouLZY+gTEvcOuuEwKrqGrht59dS3xqkrBTBxN73rHRiLP7+zcKJk09lcB76ASFQM="
    #GPG_PASSPHRASE
    - secure: "QeZVY86oOAcHMgindfUo78y6zXtZFrSybPGQkV/eY6C1fC5m+tbWm/5Yl0L7GwtcU1lzqPKbRnhvjUHwboO+bE6vRZgkp72DzvhhLuz6kZznvN4LDKiR+vOS92FTaBO+BQffoGski4juE1sFSAvU9bvfgtU9go5XnWTxwedP1lhuGCeslkWIqufFKNIZaDYKQwtOtxnVtYmD20uA9KC5XZSH42TA9py/KCM0VhOcQSHllCYPL6Ydz6aEV0pFc5A0eQwedT+SP/u6Y8CQeFND4copkL+fmsjSI3Ko60zAYE8xJPXkKg3vjhX4jcUtHoUKJJsM7dduNx7XGqwy3Fqkvbs/e3oMToLtKcE08dNUAmfh3SEWTUj7OlZB3NwptaOhmkbQ4Nun4wedi4vv/NgtszP57bJTie88XpCWBC+nDHkISv+NF/FgyowBeEVZntQIjk1gmtuqfnsEIcwsyB++zuxuVq3LqaSnFiBdGSQdpBTrntAIJByymVbr398HV6IMos5b7C8ryaXiW5KJlgRT7sLo0/0g35P4/8AT9RQqtySANBX9zFvyOHIoJWRzUNDXZBK3c15sDNmuciI1hq+rcEXULQmFlgP6YXxRr5LXsOq7ijpPwjq8686QwdVR01EOa+/6FUMy6XOqIL5A7Q4UPCPK9v36j5+Oq+X1DUZ7utw="

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

# for tags (and releases), use the tag name as the development version, and use the branch name with "-SNAPSHOT" suffix otherwise as the development version and release version:
before_install:
  - test "$TRAVIS_TAG" = "" && echo "Tag is not set -> this is a snapshot version" || echo "Tag is set -> the tag name is the version"
  - test "$TRAVIS_TAG" = "" && mvn versions:set -DnewVersion="$TRAVIS_BRANCH-SNAPSHOT" || mvn versions:set -DnewVersion="$TRAVIS_TAG"
  - openssl aes-256-cbc -K $encrypted_b9ed87107f17_key -iv $encrypted_b9ed87107f17_iv -in pubring.gpg.enc -out pubring.gpg -d
  - openssl aes-256-cbc -K $encrypted_b9ed87107f17_key -iv $encrypted_b9ed87107f17_iv -in secring.gpg.enc -out secring.gpg -d

install: true

script: mvn clean verify -P shade,sources,javadoc -Djava.version=1.6

deploy:
  provider: releases
  api_key:
    secure: vB0d2RdSz/o1qy56tqM+/vbAB7zpIJkYU/TWHhXYUbYDEEcPlseY1hpRYGSN09x0LHBLNpZSxfVPdwAagoAVWMC7YlSSJoV1W2vwicleILEywxGkZs0oB2xf200W78l43iYdnwWZa/PyihcsT+zWffiX3l0Th26Rs4AuPtWyMbBSABi1js0sR3Y036WBUF04NXaTig6fvvTZ+FEGLrRDTH6R+td2VJ4V7FlUV1FBMt3hMUfx0q3QFxdg1y5EQWPPXu3PFCcXKsU/ckK63ghJikn8N+R6Z9mPzkxbQZkuLbufAWww/a0BNc+UoyTbAbx3e5aMwNo6xyaymyKYDYdPCuGvddd1hgSMh+fDCxraXQLxemsT+fcHtc1ALrYc+ITtFGqagyS3zaodO+Jwvh7q13QRIjYyNVP76ivD7OBcWLvaVEe+AHcHudnocgBq58KGcPTXc9EaEdehdczmHE5lhEgkyuLAeieVmkX5kQvT0ciHv3BSiHTA2B5kjYy0+KvB8g0srr7ifBnT/d7IVL2NDoT8EntS2ZFrkUY1Dm/lsrm4Ho9e/FcZBZbPDsC+GAksUN6b96F438lWjUGHNM95KB9Ohno0+MCemD7onKU0ZM1x/K7CWez7wUp0gx0UQ8mARYvetp5BEBw/aD+L6Ms0ybcMVVlUqa9WcF8e36nssMs=
  file_glob: true
  file:
    - /home/travis/build/arturolszak/hycube/target/hycube-*.jar
    - /home/travis/build/arturolszak/hycube/documentation/*
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

after_deploy:
  - mvn deploy -DskipTests=true -P sign --settings .travis/settings.xml
  - rm pubring.gpg
  - rm secring.gpg

after_script: