language: java

env:
  global:
    - SONATYPE_USERNAME=hycube
    # SONATYPE_PASSWORD:
    - SONATYPE_PASSWORD=fakepassword
#    - secure: "dnOxvALDxzUeiueR61d7gVWgf7u/t3PDLRF5Xs3UNB9WkKhhIBhePVMn0GEnbEeWKUBlH5wEAkdGSJhfwZWiD0qH6vvTQyzmCm+FiCMPabRxdKDvF9gLMcRIlCjvw0wxbT26Qn+UjGFjaYixJdNqPpoj+2Bcx9fkjq9jyGm01d5Y3psJNh//HLw9asOwvCzGd9Xpzlt2mGaXESxhqBYuX2/CJGQ07o9qG47HNBvV0Ubr6SFvGm3sfVMPJbhmZxe6j7iy2Nh7zNXUbawXLiLT0yJIExkKpJvKeMdUIJ2oaTsv4bBAvMKQYvuq7GipymZDBNr1NdCAVi0aNE9Ke6rtvk10dVhXYxwtBFwbaWWnpDmQtKGuluUTHsAfCwpKbqaMc29qYSD8jEHJEscXVtMsNSknOZrVbZBO21cyzZhKaSeugvCYsqvij54ESWLulqhjcxh8G4urUUYOkJN6X7sQBT1RIT6JQm7yaFuGLarQd7TEOnsIFeD+jijeLMsLxPXQlEBdnw5Ah4XGC7LnKCE+IiRbQB8rvsFHwE2sPLPmXDQEmt9wvDi2jizd231weO8c70RnpwZSHRcxXsKsWUUKSafwji9RLTx7WgXc01VYGqaouLZY+gTEvcOuuEwKrqGrht59dS3xqkrBTBxN73rHRiLP7+zcKJk09lcB76ASFQM="
    # GPG_PASSPHRASE:
    - secure: "Jq72vAZkbGj3hR00LmMQHeqVCWnoKk70aTHe6UmjR+iLcQdDbTfxT8eY+vVQfsjuI7BNDGXbGP6LaHEpmAodyqa1+eFk4h+2ZnjsTgIit9J7YYPt7/MJ3wCNo8GqBQDAHz196fx07V1tj/qwOfo1v4MAKKGEQRjp+NPra6xM/QWOKeBBP+2/JJMaQQ1ygx0Kk7Lc5eClVyz31ftf64qSXFb7VRqvzm5DK0pY1f61fmO84mWAUejoj0PJlEWXRQFAWZzuvEgallD8XvJBd1aEzrANZF2/M/bol2TH/SjMzeBR9CdxDYLhi+ldS+Pe0zXJOJfpp2OlC0SzwQbc+njQR0qQIXJXf8pGTp8CnjYRRFXHgUSiYgzXTHlNLh1xdICc9or8AGlLN3Xp55AaoDgsCX8EN8J0PfV1hb9gaq5WUzSb0L6fwkmvp84WY0vD5dvnqSQEAskpoGS7Iz+svrJnwoSKPpxjaM5eSjeOMCaOD1PWGopA+z6rfjqTWLBRVk2U6Y3p4gUjLai+JKqXUww6qMc3M0qMxutCw8I4X/B1kUqAw/sA5n9lTSBYkqAYrwR/zrJy13f57dtBDT+T+NZakB7Pa46tAY5RpOAfE7h2PWQ2pBEATGwxHFM3OqfqCWRFOf4Z4uz1R2zlAvcV4sOGLE3B6DK8dz5nhP8aMRz1MWA="
    # ENCRYPTION_PASSWORD:
    - secure: "MoyRWJyVWRF2MQjo1a54fMAy2oKZyXzf+PkgRQaP6J7LjTc5TpQ4ScKGOfu5HS3MfNiNlzyMSnDTQ5yOYTrJ1guOahRHUfgr4EphnTAOEWXlmBGPEAek13Vq53qaCkxccfx9J+G/aq4QxyDsu1wePr/EobkRDMD3mZTzlfxvo+wKVX8PwFMSi+sw+IfHHgnCPS5WxZEJ2kopIUmZsNpf4gFmnYYZb1SfC4HKLiER2UBYXzZ68TUsfSJKNmvGuQ7JU4lL90PV8muSVMd8WQHm/UGMDNlbnXdoCS/sIgRgM7ej7aKGJSVJ+y4+5jP0YdpdBBALydTehuzL7M+VKJVcLltGCNM5Gzv0FI+hJNbLfsMKY3SQO0GU9d3d7/yYisYENCkKpYZgjjvJrIl/Z1A5hTaEm3kUvn2Cyqtm6Gl+OubBh50OrrSVoPr3LfDhZ1QyWMGAmEhQYk4bVI6A/uBo9qugnvpKuQcN4Xo0yFRMxjldxvERN6d9oblDvBXzBHJQqbR5fkOmRtK5FgaSBtVcG20fSDryjMZQQdS7SBOfZjCe4lZovFMKDMWbwpHbyM0/Zhn3nljjPwYwIO1oDboexRqB2TBNYwfZAW2uN1Cd7v29XMGrjNiEYlzjEVYUHQ3LOEStLaqryoI0zzGaJ3/0Cn4jatNrvlnuVzqR01s1GUY="

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install:
  - bash .travis/update_version.sh
  - bash .travis/decrypt_keys.sh
  - ls -l

install: true

script: bash .travis/build.sh

after_success: bash .travis/remove_keys.sh

after_failure: bash .travis/remove_keys.sh

deploy:
  provider: releases
  api_key:
    secure: vB0d2RdSz/o1qy56tqM+/vbAB7zpIJkYU/TWHhXYUbYDEEcPlseY1hpRYGSN09x0LHBLNpZSxfVPdwAagoAVWMC7YlSSJoV1W2vwicleILEywxGkZs0oB2xf200W78l43iYdnwWZa/PyihcsT+zWffiX3l0Th26Rs4AuPtWyMbBSABi1js0sR3Y036WBUF04NXaTig6fvvTZ+FEGLrRDTH6R+td2VJ4V7FlUV1FBMt3hMUfx0q3QFxdg1y5EQWPPXu3PFCcXKsU/ckK63ghJikn8N+R6Z9mPzkxbQZkuLbufAWww/a0BNc+UoyTbAbx3e5aMwNo6xyaymyKYDYdPCuGvddd1hgSMh+fDCxraXQLxemsT+fcHtc1ALrYc+ITtFGqagyS3zaodO+Jwvh7q13QRIjYyNVP76ivD7OBcWLvaVEe+AHcHudnocgBq58KGcPTXc9EaEdehdczmHE5lhEgkyuLAeieVmkX5kQvT0ciHv3BSiHTA2B5kjYy0+KvB8g0srr7ifBnT/d7IVL2NDoT8EntS2ZFrkUY1Dm/lsrm4Ho9e/FcZBZbPDsC+GAksUN6b96F438lWjUGHNM95KB9Ohno0+MCemD7onKU0ZM1x/K7CWez7wUp0gx0UQ8mARYvetp5BEBw/aD+L6Ms0ybcMVVlUqa9WcF8e36nssMs=
  file_glob: true
  file:
    - /home/travis/build/arturolszak/hycube/target/hycube-*.jar
    - /home/travis/build/arturolszak/hycube/documentation/*
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8

after_deploy:

after_script: bash .travis/clean_after_script.sh
