language: java

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
#  - openjdk6

before_install:
#  mvn --batch-mode org.apache.maven.plugins:maven-release-plugin:2.5.3:update-versions -DdevelopmentVersion="9.9.9.9-SNAPSHOT"
  mvn org.apache.maven.plugins:maven-release-plugin:2.5.3:update-versions

install: true

#script: mvn clean verify -P shade,sources,javadoc -Djava.version=1.6
script: mvn clean verify -P shade,sources -Djava.version=1.6

deploy:
  provider: releases
  api_key:
    secure: vB0d2RdSz/o1qy56tqM+/vbAB7zpIJkYU/TWHhXYUbYDEEcPlseY1hpRYGSN09x0LHBLNpZSxfVPdwAagoAVWMC7YlSSJoV1W2vwicleILEywxGkZs0oB2xf200W78l43iYdnwWZa/PyihcsT+zWffiX3l0Th26Rs4AuPtWyMbBSABi1js0sR3Y036WBUF04NXaTig6fvvTZ+FEGLrRDTH6R+td2VJ4V7FlUV1FBMt3hMUfx0q3QFxdg1y5EQWPPXu3PFCcXKsU/ckK63ghJikn8N+R6Z9mPzkxbQZkuLbufAWww/a0BNc+UoyTbAbx3e5aMwNo6xyaymyKYDYdPCuGvddd1hgSMh+fDCxraXQLxemsT+fcHtc1ALrYc+ITtFGqagyS3zaodO+Jwvh7q13QRIjYyNVP76ivD7OBcWLvaVEe+AHcHudnocgBq58KGcPTXc9EaEdehdczmHE5lhEgkyuLAeieVmkX5kQvT0ciHv3BSiHTA2B5kjYy0+KvB8g0srr7ifBnT/d7IVL2NDoT8EntS2ZFrkUY1Dm/lsrm4Ho9e/FcZBZbPDsC+GAksUN6b96F438lWjUGHNM95KB9Ohno0+MCemD7onKU0ZM1x/K7CWez7wUp0gx0UQ8mARYvetp5BEBw/aD+L6Ms0ybcMVVlUqa9WcF8e36nssMs=
  file_glob: true
  file: /home/travis/build/arturolszak/hycube/target/hycube-*.jar
  skip_cleanup: true
  on:
    tags: true


#echo 'Will change the version in pom.xml files...'
#branch=$(git rev-parse --abbrev-ref HEAD)
#
#version="$branch-SNAPSHOT"
#version="$(echo $version | sed 's/bugfix\///g')"
#version="$(echo $version | sed 's/feature\///g')"
#version="$(echo $version | sed 's/release\/skye-//g')"
#version="${version^^}"
#
#/home/agent/buildagent/tools/maven3/bin/mvn --batch-mode org.apache.maven.plugins:maven-release-plugin:2.5.3:update-versions -DdevelopmentVersion="9.9.9.9-SNAPSHOT"
#find . -name "pom.xml" -exec sed -i -e "s/9.9.9.9-SNAPSHOT/$version/g" {} +
#echo "Changed version in pom.xml files to $version"
#exit 0
